apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: demonamepsec
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 80281/my-spring-app:v76
        # imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 300m
        #     memory: 300Mi
        ports:
        - containerPort:   8080
