apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demonamepsec
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
