apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demonamepsec
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
